/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#2c0051",
        "primary-fixed": "#f0dbff",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#474747",
        "secondary-fixed-dim": "#4ae176",
        "secondary-container": "#00b954",
        "on-tertiary-container": "#2a2a2a",
        "on-secondary": "#003915",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed": "#1b1b1b",
        "primary-container": "#b76dff",
        "on-secondary-fixed": "#002109",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c6c6",
        "error": "#ffb4ab",
        "tertiary-container": "#919191",
        "primary-fixed-dim": "#ddb7ff",
        "outline": "#988d9f",
        "outline-variant": "#4d4354",
        "on-secondary-fixed-variant": "#005321",
        "inverse-primary": "#842bd2",
        "secondary": "#4ae176",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#6900b3",
        "on-primary": "#490080",
        "on-tertiary": "#303030",
        "secondary-fixed": "#6bff8f",
        "surface-tint": "#ddb7ff",
        "surface": "#131313",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#cfc2d6",
        "on-secondary-container": "#004119",
        "primary": "#ddb7ff",
        "surface-bright": "#393939",
        "surface-variant": "#353534",
        "tertiary": "#c6c6c6",
        "on-primary-container": "#400071",
        "tertiary-fixed": "#e2e2e2",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "surface-dim": "#131313",
        "background": "#131313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px", lg: "48px", xs: "4px",
        gutter: "24px", sm: "12px", base: "8px",
        "container-max": "1280px", md: "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
